"""empty message

Revision ID: 11be0b6dec69
Revises: 21e4953f1620
Create Date: 2019-03-27 10:49:57.967838

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '11be0b6dec69'
down_revision = '21e4953f1620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specie__database', sa.Column('specie', sa.String(length=45), nullable=True))
    op.drop_index('common_name', table_name='specie__database')
    op.create_unique_constraint(None, 'specie__database', ['specie'])
    op.drop_column('specie__database', 'common_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specie__database', sa.Column('common_name', mysql.VARCHAR(length=45), nullable=True))
    op.drop_constraint(None, 'specie__database', type_='unique')
    op.create_index('common_name', 'specie__database', ['common_name'], unique=True)
    op.drop_column('specie__database', 'specie')
    # ### end Alembic commands ###
