"""empty message

Revision ID: 21e4953f1620
Revises: 716bcfd61caf
Create Date: 2019-03-27 10:45:48.871157

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '21e4953f1620'
down_revision = '716bcfd61caf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specie__database', sa.Column('common_name', sa.String(length=45), nullable=True))
    op.drop_index('specie', table_name='specie__database')
    op.create_unique_constraint(None, 'specie__database', ['common_name'])
    op.drop_column('specie__database', 'specie')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specie__database', sa.Column('specie', mysql.VARCHAR(length=45), nullable=True))
    op.drop_constraint(None, 'specie__database', type_='unique')
    op.create_index('specie', 'specie__database', ['specie'], unique=True)
    op.drop_column('specie__database', 'common_name')
    # ### end Alembic commands ###
